### ISSUE TITLE
Error 500 when we open a PR in the GIN Brainglobe/test-data repo

### ISSUE THREAD

**Issue by sfmig** [brainglobe/brainglobe-workflows#17]
We get an Error 500 when we try to open a PR n the GIN Brainglobe/test-data repo.

For now we are bypassing this by pushing directly to master, but we may want to figure out why the error is happening.

**Comment by adamltyson** [comment]
I've given you and @alessandrofelder admin permissions on the repo to see if that changes anything?

**Comment by alessandrofelder** [comment]
Thanks - doesn't seem to have helped unfortunately. I still get the same error now trying to open a PR from https://gin.g-node.org/BrainGlobe/test-data/src/add-brainreg-test-data to master

**Comment by alessandrofelder** [comment]
@niksirbi suggests that this may be because the GIN web interface is renownedly buggy, and [similar (albeit not the same) issue have been reported over the last couple of years](https://github.com/G-Node/gogs/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) and unfortunately don't seem to have been active much since :cry:

**Comment by adamltyson** [comment]
Should we close this? it's not really a `brainglobe-workflows` issue.

**Comment by alessandrofelder** [comment]
> Should we close this? it's not really a brainglobe-workflows issue.

Agreed.
